import { bool, en, num, nums, removed, str, strs, type FieldSchema } from '../../../shared/schema'

export const TUN_FIELDS: FieldSchema[] = [
  bool('enable', 'Включить TUN-интерфейс: система отдаёт ядру весь трафик.'),
  en('stack', 'Реализация сетевого стека.', [
    { value: 'system', doc: 'Системный стек — стабильнее, ниже нагрузка.' },
    { value: 'gvisor', doc: 'Пользовательский стек — больше изоляции.' },
    { value: 'mixed', doc: 'TCP через system, UDP через gvisor.' },
  ]),
  str('device', 'Имя интерфейса TUN; на macOS обязателен префикс utun.'),
  strs('dns-hijack', 'Адреса host:port, DNS-запросы к которым перехватывает ядро.'),
  bool('auto-route', 'Автоматически прописать системные маршруты через TUN.'),
  bool('auto-redirect', 'Автонастройка iptables/nftables для TCP (Linux); требует auto-route.'),
  bool('auto-detect-interface', 'Автоматически определять исходящий интерфейс.'),
  bool('strict-route', 'Строгая маршрутизация: трафик не утечёт мимо TUN.'),
  strs('route-address', 'Свои маршруты вместо маршрута по умолчанию при auto-route.'),
  strs('route-exclude-address', 'Подсети, исключённые из маршрутизации через TUN.'),
  strs('route-address-set', 'Наборы правил (rule-providers) с подсетями, добавляемыми в firewall (Linux, nftables).', { ref: 'rule-set' }),
  strs('route-exclude-address-set', 'Наборы правил с подсетями, исключаемыми из маршрутизации (Linux, nftables).', { ref: 'rule-set' }),
  strs('include-interface', 'Маршрутизировать только эти интерфейсы; несовместимо с exclude-interface.'),
  strs('exclude-interface', 'Не маршрутизировать эти интерфейсы.'),
  nums('include-uid', 'Маршрутизировать только эти UID (Linux, требует auto-route).'),
  strs('include-uid-range', 'Диапазоны UID для маршрутизации, например 1000:9999.'),
  nums('exclude-uid', 'Исключённые UID.'),
  strs('exclude-uid-range', 'Исключённые диапазоны UID.'),
  strs('include-mac-address', 'Маршрутизировать только эти MAC-адреса (Linux, auto-route и auto-redirect).'),
  strs('exclude-mac-address', 'Исключённые MAC-адреса.'),
  nums('include-android-user', 'Пользователи Android, чей трафик маршрутизируется.'),
  strs('include-package', 'Android-приложения, чей трафик маршрутизируется.'),
  strs('exclude-package', 'Android-приложения, чей трафик TUN не перехватывает.'),
  num('mtu', 'MTU интерфейса TUN.'),
  bool('gso', 'Generic Segmentation Offload (Linux).'),
  num('gso-max-size', 'Максимальный размер блока GSO.'),
  num('udp-timeout', 'Таймаут NAT-сессии UDP, секунд.'),
  num('iproute2-table-index', 'Индекс таблицы маршрутизации для auto-route (Linux).'),
  num('iproute2-rule-index', 'Индекс правила ip rule (Linux).'),
  bool('endpoint-independent-nat', 'Endpoint-Independent NAT.'),
  bool('disable-icmp-forwarding', 'Не форвардить ICMP (борьба с петлёй ICMP; ping перестаёт показывать RTT).'),
  num('file-descriptor', 'Уже открытый дескриптор TUN от внешнего лаунчера.'),
  strs('inet4-route-address', 'Маршруты IPv4 (старый синтаксис).', { deprecated: removed('Meta', 'route-address') }),
  strs('inet6-route-address', 'Маршруты IPv6 (старый синтаксис).', { deprecated: removed('Meta', 'route-address') }),
  strs('inet4-route-exclude-address', 'Исключения IPv4 (старый синтаксис).', { deprecated: removed('Meta', 'route-exclude-address') }),
  strs('inet6-route-exclude-address', 'Исключения IPv6 (старый синтаксис).', { deprecated: removed('Meta', 'route-exclude-address') }),
]
